#!/usr/bin/python3
import os
import sys
import logging

import wikifolio

logging.basicConfig(level=logging.INFO)

if len(sys.argv) == 2 and os.path.exists(sys.argv[1]):
    filename = sys.argv[1]
    name, _ = os.path.splitext(filename)
    cert = wikifolio.get_id_from_name(name)
    trades = wikifolio.get_trades(cert)
    for trade in trades:
        print(repr(trade))
